/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Image } from 'react-native';
import EasyFileSystem from 'react-native-easy-file-system';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
    photoPath: null,
  };
  componentDidMount() {
    console.warn(EasyFileSystem.documentDirectory)
    EasyFileSystem.downloadAsync(
      "https://facebook.github.io/react-native/docs/assets/favicon.png",
      EasyFileSystem.documentDirectory + '/name3.png',
      {}
    )
      .then(({ uri }) => {
        console.warn("Save this uri: " + uri);
        this.setState({
          photoPath: uri
        })
      })
      .catch(error => {
        console.warn(error.message);
      });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆EasyFileSystem example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆Download, save show photo☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>

        {this.state.photoPath !== null ? (

<Image
style={{width: 66, height: 58}}
source={{uri: this.state.photoPath}}
/>
        ) : (
            <Text>Photo is loading</Text>
          )}
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
